Update nvx-remove

diff --git a/files/nvx-remove b/files/nvx-remove
--- a/files/nvx-remove
+++ b/files/nvx-remove
@@ -62,10 +62,9 @@ enter sh -lc "
     sudo sh -lc \"$cmd\"
   elif command -v doas >/dev/null 2>&1; then
     doas sh -lc \"$cmd\"
-  elif [ \"\$(id -u)\" -eq 0 ]; then
-    sh -lc \"$cmd\"
   else
-    echo 'No sudo/doas available and not root.' >&2
+    echo 'ERROR: sudo/doas not available in this container.' >&2
     exit 1
   fi
 "
+
